services:
  mysql:
    image: mysql:8.0
    container_name: booking_mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

#  app:
#    build: .
#    container_name: booking_app
#    depends_on:
#      - mysql
#    env_file:
#      - .env
#    ports:
#      - "8080:8080"

volumes:
  mysql_data: